# Generated by Django 4.0.3 on 2022-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=100)),
                ('mobile_desc', models.TextField()),
                ('mobile_img', models.TextField()),
                ('price', models.IntegerField()),
                ('specs', models.ManyToManyField(to='home.specs')),
            ],
        ),
    ]
